name: Deploy Quarto Projects

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson('["day-1"]') }} # Replace with your actual folder names

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Deploy Quarto Project
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: quarto-pub
        path: ${{ matrix.folder }}
        QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}